### ISSUE TITLE
How to copy files inside environment, Read-only file system?

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#32]
I have such command in hook `.yml`:

```
- name: Copy settings.local.php
  command: "fin exec sudo cp /var/www/www/sites/default/settings.local.php.docksal  /var/www/www/sites/default/settings.local.php"
  args:
    chdir: "{{ docroot_path }}"
```
There is an error:

>  stderr: 'cp: cannot create regular file ‘/var/www/www/sites/default/settings.local.php’: Read-only file system'

I tried without `fin exec`, but there is Ansible errors with sudo.
