### ISSUE TITLE
 Read-only file system is a critical issue in some cases

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#36]
For example, I have such a task in `.andock/hooks/update_tasks.yml`:

```
- name: Install Behat Dependencies
  command: fin composer install
  args:
    chdir: "{{ environment_path }}/tests/behat"
```
This directory is under a Git repo, so I cannot mount the directory as writable volume, and composer cannot modify `composer.lock`:

`file_put_contents(./composer.lock): failed to open stream: Read-only file system`

The second example, I have `gulp` directory in the project root, this directory is under a Git repo, so I cannot mount the directory as writable volume, but `node` requires write permissions for `gulp/package-lock.json` and `gulp/node_modules`.

**Comment by christianwiedemann** [comment]
Installing libs with composer/npm etc. should be done in the build phase. Or do I missunderstand something. But maybe it makes sense to make the read only setting configurable.

**Comment by ArtuGit** [comment]
@christianwiedemann 

> Installing libs with composer/npm etc. should be done in the build phase
In both cases, it is performed inside Docksal, but we cannot run `fin` on build phase.

> But maybe it makes sense to make the read only setting configurable.

Yes, or allowing to run `fin` on build phase with writing to any directory.

**Comment by christianwiedemann** [comment]
You can run fin command on build phase
You two posibilties: (The samples using acquia blt. Can be everything you want)
1:) Default without docksal environment with "fin rc": 
```
fin rc --image=docksal/cli:2.6-php7.2 -T /var/www/vendor/bin/blt source:build:frontend
```
2:) With build docksal environment:
Add `fin_up_during_build: true` To your andock.yml

**and:**
```
fin exec -T /var/www/vendor/bin/blt source:build:frontend
```

**Comment by christianwiedemann** [comment]
```
- name: Composer install
  command: "fin rc --image=docksal/cli:2.6-php7.2 -T composer install"
  args:
    chdir: "{{ build_path }}"

- name: "Build frontend"
  command: "fin rc --image=docksal/cli:2.6-php7.2 -T /var/www/vendor/bin/blt source:build:frontend"
  args:
    chdir: "{{ build_path }}"

- name: "Validate frontend"
  command: "fin rc --image=docksal/cli:2.6-php7.2 -T /var/www/vendor/bin/blt tests:frontend:run"
  args:
    chdir: "{{ build_path }}"

```
